setwd("~/Desktop/R")
data <- read.table("household_power_consumption.txt", header = TRUE, sep= ";", col.names = c("date", "time", "globalactivepower", "globalreactivepower", "Voltage", "globalintensity", "submetering1", "submetering2", "submetering3"))
subdata <- subset(data, data$date == "1/2/2007"| data$date == "2/2/2007")
subdata$date <- as.Date(subdata$date, format="%d/%m/%Y")
subdata$time <- strptime(subdata$time, format="%H:%M:%S")
subdata[1:1440,"time"] <- format(subdata[1:1440,"time"],"2007-02-01 %H:%M:%S")
subdata[1441:2880,"time"] <- format(subdata[1441:2880,"time"],"2007-02-02 %H:%M:%S")
plot(subdata$time, subdata$submetering1, type = "n", xlab = "", ylab= "Energy sub metering")
lines(subdata$time, as.numeric(as.character(subdata$submetering1)))
lines(subdata$time, as.numeric(as.character(subdata$submetering2)), col= "red")
lines(subdata$time, as.numeric(as.character(subdata$submetering3)), col = "blue")
legend("topright", lty=1, col=c("black","red","blue"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
